### ISSUE TITLE
Create data pattern for the EEPROM

### ISSUE THREAD

**Issue by aylons** [lnls-dig/fmc-5POF-hw#6]
A model for the EEPROM should be defined. It could contain the board identification, the Vadj level and follow the IPMI standard. If possible, it should also store the assembly option of the board.

@henrique-silva , could you please help me here?

**Comment by henrique-silva** [comment]
The Vadj levels already have a standard field in the FRU created by the openMMC module. I'll create a custom field for the assembly option.
How will this information be stored? We can use strings or any other predefined code, there's no restriction regarding the data type here. It shouldn't be too long though, we don't have that much space in the EEPROM (:

**Comment by aylons** [comment]
One bit per channel 1-5, 1 is receivers, 0 is transmitter, seems great. You
may change to 1 byte per channel if this is easier to read/write.

The preferred Vadj for FMC-5CH-POF is 3.3V

2017-03-10 9:56 GMT-03:00 Henrique A. Silva <notifications@github.com>:

**Comment by henrique-silva** [comment]
Do you want to keep this binary file in this repository?
I could export it from the openMMC FRU modules (they are some simple c functions that only fill and order some structs).

**Comment by aylons** [comment]
There would be 6 files, one for each assembly option, right?

The standard don't call for a unique serial number, does it? If not, yes,
we could have these 6 binary stored here as a resource.

2017-03-10 10:13 GMT-03:00 Henrique A. Silva <notifications@github.com>:

**Comment by henrique-silva** [comment]
Unfortunately each board has its own "Board Info" field, which includes the board Serial Number and Part Number, as well as the Manufacturing Time.
I'll put the binary building code in a different repo with instructions on how to build the FRU Info.

**Comment by aylons** [comment]
Ok, the documentation in the manual should be enough for this issue.

An EEPROM generator/recorder script is due, however.

**Comment by henrique-silva** [comment]
Just for the record, the script to generate the EEPROM FRU data can be accessed at [fru-build](https://github.com/lnls-dig/fru-build).
